title: MoonCha's Notepad
subtitle: Documentation for Life
description: >-
  See how MoonCha lives his life.
email: moonchang@postech.ac.kr

url: "https://mooncha.github.io"
baseurl: ""
repository: MoonCha/mooncha.github.io

remote_theme: mmistakes/minimal-mistakes@4.28.0
minimal_mistakes_skin: default
locale: en-US

author:
  name: MoonCha
  avatar: https://avatars0.githubusercontent.com/u/14259596
  bio: Documentation for Life
  email: moonchang@postech.ac.kr
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/MoonCha

analytics:
  provider: google-universal
  google:
    tracking_id: UA-126796569-1

highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

after_footer_scripts:
  - /assets/js/mermaid.min.js
  - /assets/js/mermaid-init.js

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  - scope:
      path: ""
    values:
      layout: single
